### ISSUE TITLE
CORS Error on Fetch

### ISSUE THREAD

**Issue by ajayns** [kitconcept/plone.restapi-react-tutorial#4]
I've built a basic app as per the tutorial here and to fetch from api I use the following code:
```javascript
fetch(
        'http://localhost:8080/Plone/front-page', {
          headers: {
            'Accept': 'application/json', 
          }
        }
      )
```

For the API, I've cloned `plone.restapi` and have it up and running at `localhost:8080` and I've checked it's functionality with Postman as well. 

The problem seems to arise when I make the fetch request from the React App, it seems to catch this error in the console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/Plone/front-page. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

And so fails to load any data from the API. @tisto Any ideas on what to do?

**Comment by ajayns** [comment]
[UPDATE]
I've installed this Chrome extension which temporarily fixes the issue for my local development environment called 'Allow-Control-Allow-Origin:*". Now the app seems to be working fine.

**Comment by tisto** [comment]
@ajayns yep. that's what you should use. We should add a note to the tutorial...
